# Generated by Django 5.2.1 on 2025-05-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='email_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone',
            new_name='telefone_usuario',
        ),
    ]
