# Generated by Django 5.2.1 on 2025-07-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_produto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Produto",
        ),
    ]
