# Generated by Django 5.2.1 on 2025-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alocacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alocacao",
            name="imagem_alocacao",
            field=models.ImageField(
                blank=True, null=True, upload_to="alocacao_imagens/"
            ),
        ),
    ]
