# Generated by Django 5.2.1 on 2025-07-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_produto", models.CharField(max_length=100)),
                ("descricao_produto", models.TextField()),
                ("preco_produto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade_estoque", models.IntegerField()),
                ("imagem_produto_url", models.URLField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "dono_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
