# Generated by Django 5.2.1 on 2025-07-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="imagem_produto_url",
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="produtos_imagens/"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade_estoque",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
